### ISSUE TITLE
Make the 9 Images smaller and pop to full size when clicked

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#31]
use bootstrap to make images appear smaller like instagram and pop to full size when clicked on

**Comment by LeCeee** [comment]
I'd like to resolve this issue.

**Comment by adlyloukil** [comment]
@LeCeee Thank you so much for your quality contribution there are a few more issues if you would like to contribute that would be fantastic!
