### ISSUE TITLE
Create a  Simple High Quality Banner in .PNG format

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#49]
Transparent background and Text .PNG banner and add it to the repository!

**Comment by Ilyeo** [comment]
could I take this one?

**Comment by adlyloukil** [comment]
@Ilyeo Sure

**Comment by Ilyeo** [comment]
@adlyloukil Oh sorry I confused, I read wrong I thought you got the asset for the banner

**Comment by adlyloukil** [comment]
@Ilyeo Oh no problem, yeah i'm looking for someone to contribute a new asset to replace the old one. Thank you anyway for your willingness to contribute!

**Comment by suyasha0** [comment]
@adlyloukil Replace which banner? Simple Pics?

**Comment by adlyloukil** [comment]
@suyasha0 yeah that's correct. I am looking for High Quality replacement because the current one is really low quality and blurry

**Comment by soulspark666** [comment]
#52 replaced the banner to something else, please check if you like it.
