### ISSUE TITLE
Replace the 9 images with High Quality HD Photos of a theme of your choosing!

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#50]
Replace the 9 images with High Quality pictures of a theme of your choice!

**Comment by soulspark666** [comment]
Can I do it?

**Comment by adlyloukil** [comment]
Yes @soulspark666 looking forward to your contribution!

**Comment by soulspark666** [comment]
Did something in #52 , please check it out!
