### ISSUE TITLE
[Hacktoberfest 2018] Remove the second scroll bar so that the image when clicked is unscrollable

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#56]
Make the image when clicked to be unscrollable!
![scroll bar](https://user-images.githubusercontent.com/22683645/47255883-febb9f00-d46e-11e8-88e5-27bbc91babf9.PNG)

**Comment by lisa-broedlin** [comment]
I will do it.

**Comment by lisa-broedlin** [comment]
I did this.

**Comment by adlyloukil** [comment]
Thank you @lisa-broedlin
