### ISSUE TITLE
Remove the extra space at the bottom of the responsive mobile device version of the website

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#64]
Refer to image below:

![extraspace](https://user-images.githubusercontent.com/22683645/47256796-5103bc80-d47d-11e8-98ca-c08e66afb942.PNG)

**Comment by maryfranceshull** [comment]
I'll look at this one!

**Comment by adlyloukil** [comment]
still open.

**Comment by adlyloukil** [comment]
@rusty-electron Thank you, issue solved
