### ISSUE TITLE
[Hacktoberfest 2018] Mobile version of the website has empty space PLEASE REMOVE IT

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#79]
Hacktoberfest 2018 Remove the white space of the responsive mobile version of the website.

![white space](https://user-images.githubusercontent.com/22683645/47307826-ef338600-d627-11e8-84d2-d3acd42e086c.PNG)

**Comment by praveenscience** [comment]
Looking into it... 😇

**Comment by praveenscience** [comment]
Fixed it...

![image](https://user-images.githubusercontent.com/1830380/47308104-9a443f80-d628-11e8-91a9-813299621eee.png)

![image](https://user-images.githubusercontent.com/1830380/47308109-a4663e00-d628-11e8-9ebe-e95aebbca2d3.png)

Making a PR. 😄

**Comment by praveenscience** [comment]
Fixed, PR: #81.
