### ISSUE TITLE
[Hacktoberfest 2018] Centre the image when clicked on the mobile version of the responsive website and the PC version of it [SEE IMAGE BELOW]

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#80]
Hacktoberfest 2018 , Centre the image when its clicked refer to image below.

![imageuncentredwhenclicked](https://user-images.githubusercontent.com/22683645/47307917-23a74200-d628-11e8-9636-2ff71f2231a0.PNG)

**Comment by praveenscience** [comment]
You mean both horizontal and vertical?

**Comment by adlyloukil** [comment]
@rusty-electron Thank you, issue solved

**Comment by adlyloukil** [comment]
@rusty-electron @
