### ISSUE TITLE
[Hacktoberfest2018] Use Bootstrap to resize the images into a 3x3 grid in the centre

### ISSUE THREAD

**Issue by adlyloukil** [adlyloukil/Hacktoberfest-2018-Operation-Barebones-SimplePics#9]
Resize the current images and place them in the middle of the page similar to instagram.

**Comment by viveksdf** [comment]
@adlyloukil Done but you need to resolve conflicts 😞

**Comment by BhathiyaTK** [comment]
Pleasure to work with this issue.
